### ISSUE TITLE
Readme contains link to Ignite docs, that link is 404ing

### ISSUE THREAD

**Issue by crismanNoble** [intuit/Ignite#50]
In the usage section, there is a link to https://intuit.github.io/Ignite/, which is currently a 404. Looking at the gh-pages branch it looks like there is an extra path level introduced and https://intuit.github.io/Ignite/Ignite does resolve, although most resources on the page are pointing at https://intuit.github.io/Ignite/*.* and 404ing themselves, which leads me to believe that the extra Ignite path is the issue.

**Comment by hipstersmoothie** [comment]
@crismanNoble fixed!

**Comment by hipstersmoothie** [comment]
@crismanNoble thanks for trying out ignite!  If you encounter any more problems files issues!

You still at classy?

**Comment by crismanNoble** [comment]
Just came back to Intuit 😊

**Comment by hipstersmoothie** [comment]
😮 Awesome! We should grab lunch sometime
